# Generated by Django 4.2 on 2023-04-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='description',
        ),
        migrations.AddField(
            model_name='libro',
            name='resena',
            field=models.TextField(null=True, verbose_name='Reseña'),
        ),
    ]
